[package]
name = "crusty_gba"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
byteorder = "1.5.0"
num = "0.4"
num-derive = "0.4"
num-traits = "0.2"
sdl2 = "0.36.0"
